# -*- coding: utf-8 -*-
"""LVADSUSR92-kamalakannan-lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nPp62zEb2OXN3sDOxmDv0PSf9nnrOlVI
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('expenses.csv')
df.columns

#handling missing Values
df.isnull().sum()

#handling OUtliers
Q1 = df['charges'].quantile(0.25)
Q3 = df['charges'].quantile(0.75)
IQR = Q3 - Q1
lower_limit = Q1 - (1.5*IQR)
upper_limit = Q3 + (1.5*IQR)
df = df[~(df['charges'] < lower_limit) | (df['charges'] > upper_limit)]

lb = LabelEncoder()

df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

#Visualisation
plt.figure(figsize = (6,6), dpi = 150)
sns.histplot(data = df, x ='charges',hue = 'region',kde = True)

plt.figure(figsize = (8,7), dpi = 150)
sns.pairplot(df)
plt.show()

plt.figure(figsize = (8,7), dpi = 150)
sns.boxplot(data = df, y = 'charges', x = 'region')

plt.figure(figsize = (8,7), dpi = 150)
sns.boxplot(data = df, y = 'charges', x = 'sex')

#Feature Selection
X = df.drop('charges', axis=1)
y = df['charges']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,random_state=7)

#Training and Prediction
model_1 = LinearRegression()
model_1.fit(X_train,y_train)
y_pred = model_1.predict(X_test)

#Evaluation
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)



