# -*- coding: utf-8 -*-
"""LVADSUSR92-kamalakannan-IA2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_nhfwrfT5ryf-zdGcjVwgX2U-rOxpGk
"""

#1
import numpy as np
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],[[255,255,0],[255,0,255],[0,255,255]],[[127,127,127],[200,200,200],[50,50,50]]])
print(rgb_image)
def rgb_to_grayscale(rgb_image):

    coefficients = np.array([0.2989, 0.5870, 0.1140])

    grayscale_image = np.dot(rgb_image, coefficients)

    return grayscale_image
rgb_image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                      [[255, 255, 0], [255, 0, 255], [0, 255, 255]],
                      [[127, 127, 127], [200, 200, 200], [50, 50, 50]]])
grayscale_image = rgb_to_grayscale(rgb_image)
print(grayscale_image)

#2
import numpy as np

def health_data(splno, attributes):
    healthdata = np.random.normal(loc=0, scale=1, size=(splno,attributes))

    normalized_healthdata = (healthdata - np.mean(healthdata, axis=0)) / np.std(healthdata, axis=0)

    return normalized_healthdata


splno = 10
attributes = 3

health_datagen =health_data(splno,attributes)


print(health_datagen[:2])

#3
arr_3d = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]
                    ])
arr_flattend = arr_3d.flatten()
print(arr_flattend)
arr_2d = arr_flattend.reshape(2,4)
print(arr_2d)

#4
import numpy as np

old_per = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

new_per = np.array([[11, 22, 33],
                    [44, 55, 66],
                    [77, 88, 99]])

def performance_score(performance):

    return np.mean(performance, axis=1)


old_scores = performance_score(old_per)
new_scores = performance_score(new_per)

comparing = np.column_stack((old_scores, new_scores))


print("Athlete  Old Score  New Score")
for i, (old_score, new_score) in enumerate(comparing):
    print(f"Athlete {i+1}:   {old_score}      {new_score}")

#5

#6
def apply_adjustment_factors(city_temperatures, adjustment_factors):

    adjusted_factors = adjustment_factors.reshape(1, -1)
    adjusted_temperatures = city_temperatures * adjusted_factors

    return adjusted_temperatures
city_temperatures = np.array([
    [20, 25, 30, 28],
    [15, 18, 22, 20],
    [10, 12, 14, 16]
])
adjustment_factors = np.array([0.95, 0.98, 1.05, 1.02])

adjusted_temperatures = apply_adjustment_factors(city_temperatures, adjustment_factors)

print("Original temperatures:")
print(city_temperatures)
print("\nAdjusted temperatures:")
print(adjusted_temperatures)

#7
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Age': [25, 30, 35, 40, 45, 50, 55],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']
}

final = [(data['Name'][i], data['City'][i]) for i in range(len(data['Name']))
                 if data['Age'][i] < 45 and data['Department'][i] != 'HR']

for name, city in final:
    print(f"Name: {name}, City: {city}")

#8
data1 = {'Product':['Apples','Bananas','Cherries','Dates','Elderberries','Flour','Grapes'],
         'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruit'],
         'Price':[1.2,0.5,3.0,2.5,4.0,1.5,2.0],
         'promotion':[True,False,True,True,False,True,False]}
df1 = pd.DataFrame(data1)
filter  = df[((df['Category'] == 'Fruit') & (df['Price'] > df['Price'].agg('avg')))]

#9
import pandas as pd
Employee_data = {'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
                 'Department': ['HR', 'IT', 'Finance', 'IT'],
                 'Manager': ['John', 'Rachel', 'Emily', 'Rachel']}

Project_data = {'Employee': ['Alice', 'Charlie', 'Eve'],
                'Project': ['P1', 'P3', 'P2']}

employees_df = pd.DataFrame(Employee_data)
projects_df = pd.DataFrame(Project_data)

merged_df = pd.merge(projects_df, employees_df, on='Employee', how='left')

merged_df = merged_df.fillna('Unassigned')

department_overview = merged_df.groupby(['Department', 'Manager']).agg({'Project': lambda x: ', '.join(x)}).reset_index()

print(department_overview)

#10
import pandas as pd


data = {
    'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Sales': [70000, 50000, 30000, 40000, 60000]
}
df = pd.DataFrame(data)


dep_sales = df.groupby('Department')['Sales'].sum()

dep_counts = df['Department'].value_counts()
average_sales_per_salesperson = dep_sales / dep_counts

ranked_departments = average_sales_per_salesperson.sort_values(ascending=False)

print("Average Sales per Salesperson in Each Department:")
print(average_sales_per_salesperson)

print("\nRanked Departments based on Average Sales per Salesperson:")
print(ranked_departments)