# -*- coding: utf-8 -*-
"""lvadsusr92_kamalakannan_IA2 Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fax3AERqkG98-gg49rU1wtijeudQaz37
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv("winequality-red.csv")

df

df.isnull().sum()

impute = SimpleImputer(strategy='median')
df = pd.DataFrame(impute.fit_transform(df),columns = df.columns)
df

df.isnull().sum()

z_scores = np.abs((df - df.mean()) / df.std())
df = df[(z_scores < 3).all(axis=1)]

q1=df['fixed acidity'].quantile(0.25)
q3=df['fixed acidity'].quantile(0.75)
iqr=q3-q1
l_limit=q1-(iqr*1.5)
u_limit=q3+(iqr*1.5)
df=df[(df['fixed acidity']>l_limit) & (df['fixed acidity']<u_limit)]
df

plt.figure(figsize = (8,7), dpi = 150)
sns.boxplot(data = df, y = 'fixed acidity', x = 'quality' )

df['quality_category'] = np.where(df['quality'] >= 7, 'good', 'bad')
df

sns.pairplot(df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'quality_category']],
             hue='quality_category')
plt.show()

X = df.drop(['quality', 'quality_category'], axis=1)
y = df['quality_category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

k = 4
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train_scaled, y_train)

y_pred = knn.predict(X_test_scaled)
print("\nClassification report:")
print(classification_report(y_test, y_pred))
print("\nAccuracy:", accuracy_score(y_test, y_pred))